# Setup a elastic search server & kibana for testing mappings or inspecting production images.
#
# Usage
# =====
# 1. $ mkdir esdata
# 2. Extract production data to esdata/ if you want
# 3. $ docker-compose up
#

version: '2'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.0
    volumes:
      - "./esdata:/usr/share/elasticsearch/data"
      - "./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
    ports:
      - "62222:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.1.0
    ports:
      - "62223:5601"
